CódigoProyecto/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
  
use App\Http\Controllers\GoogleController;
use App\Http\Controllers\GameController;
use App\Http\Controllers\SoporteController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('editar/{id?}', "UserController@edit")->name('users.edit');
Route::delete('eliminar/{id?}', "UserController@destroy")->name('users.destroy');
Route::post('update{id?}', "UserController@update")->name('users.update');


Route::resource('games', 'GameController');
Route::get('list', 'GameController@list');



Route::resource('user', 'UserController');



Route::get('editar/{id}', 'UserController@edit');
Route::get('show/{id}', 'UserController@show');


Route::get('comprar/{id?}', 'GameController@comprar')->name('games.comprar');
Route::get('edit/{id?}', 'GameController@edit')->name('games.edit');
Route::delete('destroy/{id?}', 'GameController@destroy')->name('games.destroy');
Route::GET('create', 'GameController@create')->name('games.create');
Route::POST('store', 'GameController@store')->name('games.store');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Grupo que nos permite redireccionar a una pagina distitan si el usuario es administrador
Route::group(['middleware' => 'admin'], function () {
    Route::get('/games', 'GameController@index');

});

//Rutas para el pago con PayPal
Route::post('payment', 'PayPalController@payment')->name('payment');
Route::get('cancel', 'PayPalController@cancel')->name('payment.cancel');
Route::get('payment/success', 'PayPalController@success')->name('payment.success');

//Rutas para el inicio de sesión con Google
Route::get('auth/google', [GoogleController::class, 'redirectToGoogle']);
Route::get('auth/google/callback', [GoogleController::class, 'handleGoogleCallback']);

//Ruta de la función filtrar por plataforma
Route::post("filtrar", [GameController::class, 'FiltrarPlataforma']);
Route::post("FiltrarTitulo", [GameController::class, 'FiltrarTitulo']);



Route::get('contactanos', [SoporteController::class, 'index'])->name('soporte.index');

Route::post('contactanos', [SoporteController::class, 'store'])->name('soporte.store');

Route::resource('plataforma', 'PlataformaController');
Route::resource('genero', 'GeneroController');


Route::group(['middleware'=>'auth'], function(){
    Route::get('/', function () {
        return view('welcome');
    });
});

CódigoProyecto/app/Game.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Game extends Model
{
    protected $fillable = [
        'titulo', 'genero', 'edicion', 'plataforma','precio',
    ];
}

CódigoProyecto/app/Http/Controllers/GameController.php
<?php

namespace App\Http\Controllers;

use App\Game;
use Illuminate\Http\Request;
use Redirect;
use PDF;
use DB;

use Illuminate\Support\Facades\Storage;



class GameController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['games'] = Game::orderBy('id','asc')->paginate(10);

        return view('game.List',$data);
    }

    public function list()
    {
        $data['games'] = Game::orderBy('id','asc')->paginate(10);
        $games = $data['games'];
        $plataformas = DB::table('plataformas')->paginate(100);

        return view('game.ListNo', compact('games', 'plataformas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('game.Create',['plataformas' => DB::table('plataformas')->paginate(100), 'generos' => DB::table('generos')->paginate(100) ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'titulo' => 'required',
            'genero' => 'required',
            'edicion' => 'required',
            'plataforma' => 'required',
            'precio' => 'required',
            'foto' => 'required'
        ]);

        //Game::create($request->all());
        $games = request()->except('_token');

            
            if($request->hasFile('foto')){
                $games['foto']=$request->file('foto')->store('uploads', 'public');
            }

          Game::insert($games);

           return Redirect::to('games');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $where = array('id' => $id);
        $game_info = Game::where($where)->first();

        $plataformas = DB::table('plataformas')->paginate(100);
        $generos = DB::table('generos')->paginate(100);

        return view('game.Edit', compact('game_info', 'plataformas', 'generos'));

    }

    public function comprar($id)
    {
        $where = array('id' => $id);
        $data['game_info'] = Game::where($where)->first();

        return view('game.Show', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'titulo' => 'required',
            'genero',
            'edicion',
            'plataforma',
            'precio',
        ]);

        $games = $request->except(['_token','_method']);

        if($request->hasFile('foto')){
            $game = Game::findOrFail($id);

            Storage::delete('public/' . $game->foto);
            
            $games['foto']=$request->file('foto')->store('uploads', 'public');
        }

        Game::where('id','=',$id)->update($games);
        return Redirect::to('games');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $game = Game::findOrFail($id);

        if(Storage::delete('public/' . $game->foto)){

            Game::where('id',$id)->delete();

        }

        return Redirect::to('games');
    }

    //filtrar por plataforma
    public function FiltrarPlataforma(){

        $plataforma = request('plataforma') ;
        $games = DB::table('games')->where('plataforma', '=', $plataforma)->paginate(100);
        return view('game.ListNo', ['games'=>$games , 'plataformas' => DB::table('plataformas')->paginate(100)]);
    }

    //filtrar por Titulo
    public function FiltrarTitulo(){

        $titulo ="%" . request('titulo') . "%" ;
        $games = DB::table('games')->where('titulo', 'like', $titulo)->paginate(100);
        return view('game.ListNo', ['games'=>$games, 'plataformas' => DB::table('plataformas')->paginate(100),]);

    }

}

CódigoProyecto/resources/views/game/Create.blade.php
@extends('layouts.app')

@section('content')
<h2 style="margin-top: 12px;" class="text-center">Añadir Videojuego</a></h2>
<br>

<form action="{{ route('games.store') }}" method="POST" enctype="multipart/form-data" >
@csrf

<div class="">
    <div class="col-md-8">
        <div class="form-group">
            <strong>Titulo</strong>
            <input type="text" name="titulo" class="form-control" placeholder="Titulo" required>
            <span class="text-danger">{{ $errors->first('titulo') }}</span>
        </div>
    </div>
    <div class="col-md-8">
        <div class="form-group">
            <strong>Género</strong>
            <select name="genero" id="1" class="form-control form-control-sm">
                     @foreach ($generos as $genero)
                        <option value="{{ $genero->nombre }}">{{$genero->nombre}}</option>
                     @endforeach
                </select>
            <span class="text-danger">{{ $errors->first('genero') }}</span>
        </div>
    </div>
    <div class="col-md-8">
        <div class="form-group">
            <strong>Edicion</strong>
            <input class="form-control" col="4" name="edicion" placeholder="Edicion" required></textarea>
            <span class="text-danger">{{ $errors->first('edicion') }}</span>
        </div>
    </div>
    <div class="col-md-8">
        <div class="form-group">
            <strong>Plataforma</strong>
            <select name="plataforma" id="1" class="form-control form-control-sm">
                     @foreach ($plataformas as $plataforma)
                        <option value="{{ $plataforma->nombre }}">{{$plataforma->nombre}}</option>
                     @endforeach
                </select>
            <span class="text-danger">{{ $errors->first('plataforma') }}</span>
        </div>
    </div>
    <div class="col-md-8">
        <div class="form-group">
            <strong>Precio</strong>
            <input class="form-control" col="4" name="precio" placeholder="Precio" required></textarea>
            <span class="text-danger">{{ $errors->first('precio') }}</span>
        </div>
    </div>

    <div class="col-md-8">
        <div class="form-group">
            <strong>Foto</strong>
            <input type="file" name="foto" id="foto" class="form-control" required>
            <span class="text-danger">{{ $errors->first('foto') }}</span>
        </div>
    </div>

    <div class="col-md-8">
        <button type="submit" class="btn btn-primary">Aceptar</button>
    </div>
</div>

</form>
@endsection

CódigoProyecto/resources/views/game/Edit.blade.php
@extends('layouts.app')

@section('content')
<h2 style="margin-top: 12px;" class="text-center">Editar Videojuego</a></h2>
<br>

<form action="{{ url('/games/' . $game_info->id) }}" method="post" enctype="multipart/form-data"> 
    @csrf
    {{ method_field('PATCH') }}

    <div class="">
    <div class="col-md-8">
            <div class="form-group">
                <strong>Foto</strong>
                <img src="{{ asset('storage'). '/' . $game_info->foto }}" width="100" height="180"  alt="">
                <input type="file" name="foto" class="form-control" >
                <span class="text-danger">{{ $errors->first('foto') }}</span>
            </div>
        </div>
        <div class="col-md-8">
            <div class="form-group">
                <strong>Titulo</strong>
                <input type="text" name="titulo" class="form-control" placeholder="Titulo" value="{{ $game_info->titulo }}" required>
                <span class="text-danger">{{ $errors->first('titulo') }}</span>
            </div>
        </div>
        <div class="col-md-8">
            <div class="form-group">
                <strong>Género</strong>
                <select name="genero" id="1" class="form-control form-control-sm">
                     @foreach ($generos as $genero)
                        @if ($genero->nombre == $game_info->genero)
                        <option value="{{ $genero->nombre }}" selected>{{$genero->nombre}}</option>
                        @else
                        <option value="{{ $genero->nombre }}">{{$genero->nombre}}</option>
                        @endif
                       
                     @endforeach
                </select>
                <span class="text-danger">{{ $errors->first('genero') }}</span>
            </div>
        </div>
        <div class="col-md-8">
            <div class="form-group">
                <strong>Edicion</strong>
                <input type="text" name="edicion" class="form-control" placeholder="Edicion" value="{{ $game_info->edicion }}" required>
                <span class="text-danger">{{ $errors->first('edicion') }}</span>
            </div>
        </div>
        <div class="col-md-8">
            <div class="form-group">
                <strong>Plataforma</strong>
                <select name="plataforma" id="1" class="form-control form-control-sm">
                     @foreach ($plataformas as $plataforma)
                        @if ($plataforma->nombre == $game_info->plataforma)
                        <option value="{{ $plataforma->nombre }}" selected>{{$plataforma->nombre}}</option>
                        @else
                        <option value="{{ $plataforma->nombre }}">{{$plataforma->nombre}}</option>
                        @endif
                     @endforeach
                </select>
                <span class="text-danger">{{ $errors->first('plataforma') }}</span>
            </div>
        </div>

        <div class="col-md-8">
            <div class="form-group">
                <strong>Precio</strong>
                <input type="text" name="precio" class="form-control" placeholder="Precio" value="{{ $game_info->precio }}" required>
                <span class="text-danger">{{ $errors->first('precio') }}</span>
            </div>
        </div>

        <div class="col-md-8">
            <button type="submit" class="btn btn-primary">Aceptar</button>
        </div>
    </div>

</form>
@endsection

CódigoProyecto/resources/views/game/Layout.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Game Warrior</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <meta charset="UTF-8">
    <meta name="description" content="Game Warrior">
    <meta name="keywords" content="warrior, game, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Favicon -->
    <link href="{{ asset('img/favicon.ico') }}" rel="shortcut icon" />

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,500,500i,700,700i" rel="stylesheet">

    <!-- Stylesheets -->
    <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}" />
    <link rel="stylesheet" href="{{ asset('css/font-awesome.min.css') }}" />
    <link rel="stylesheet" href="{{ asset('css/owl.carousel.css') }}" />
    <link rel="stylesheet" href="{{ asset('css/style.css') }}" />
    <link rel="stylesheet" href="{{ asset('css/animate.css') }}" />


    <style>
    body {
        background-color: #ffb320;
    }

    .container2 {
        background: #ffb320;
        padding: 4%;
        border-top-left-radius: 0.5rem;
        border-bottom-left-radius: 0.5rem;
    }
    </style>

</head>

<body>
    <header class="header-section">
        <div class="container">
            <!-- logo -->
            <a class="site-logo" href="/">
                <img src="{{ asset('img/logo.png') }}" alt="">
            </a>
            <div class="user-panel">
                <a href="/login">Iniciar Sesión</a> / <a href="/register">Registro</a>
            </div>
            <!-- responsive -->
            <div class="nav-switch">
                <i class="fa fa-bars"></i>
            </div>
            <!-- site menu -->
            <nav class="main-menu">
                <ul>
                    <li><a href="/">Home</a></li>
                    <li><a href="{{ action('GameController@index') }}">Store</a></li>
                    <li><a href="">Blog</a></li>
                    <li><a href="">Forums</a></li>
                    <li><a href="">Contact</a></li>
                </ul>
            </nav>
        </div>


        
    </header>
    <div class="container2">
    <br>
        @yield('content')
    </div>
</body>

</html>

CódigoProyecto/resources/views/game/List.blade.php
@extends('layouts.app')
   
@section('content')
   <div class="">
        <div class="col-12">
         
         <a href="{{ route('user.index') }}" class="btn btn-primary mb-2 float-right">Lista de usuarios</a>
          
          <table class="table table-bordered table-dark table-hover text-center" id="laravel_crud">
           <thead>
              <tr>
                  <th>Imagen</th>
                 <th>Id</th>
                 <th>Titulo</th>
                 <th>Genero</th>
                 <th>Edicion</th>
                 <th>Plataforma</th>
                 <th>Precio</th>
                 <td colspan="2">Action</td>
              </tr>
           </thead>
           <tbody>
              @foreach($games ?? '' as $game)
              <tr>
               <td>
                  <img src="{{ asset('storage'). '/' . $game->foto }}" width="100" height="140"  alt="" class="rounded img-fluid">
               </td>
                 <td class="align-middle">{{ $game->id }}</td>
                 <td class="align-middle">{{ $game->titulo }}</td>
                 <td class="align-middle">{{ $game->genero }}</td>
                 <td class="align-middle">{{ $game->edicion }}</td>
                 <td class="align-middle">{{ $game->plataforma }}</td>
                 <td class="align-middle">{{ $game->precio }}€</td>
                 <td class="align-middle"><a href="{{ route('games.edit',$game->id)}}" class="btn btn-primary">Editar</a></td>
                 <td class="align-middle">
                 <form action="{{ route('games.destroy', $game->id)}}" method="post">
                  {{ csrf_field() }}
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Eliminar</button>
                </form>
                </td>
              </tr>
              @endforeach
           </tbody>
          </table>
          <a href="{{ route('games.create') }}" class="btn btn-success mb-2">Añadir Nuevo Videojuego</a>
          <a href="{{ route('plataforma.create') }}" class="btn btn-success mb-2">Añadir Nueva Plataforma</a>
          <a href="{{ route('genero.create') }}" class="btn btn-success mb-2">Añadir Nuevo Género</a>
       </div> 

       <div class="ml-3">
         {{ $games->links() }} 
       </div>
       
   </div>
 @endsection

CódigoProyecto/resources/views/game/ListNo.blade.php
@extends('layouts.app')

@section('content')
   <div class="">
      <!-- mensaje de compra correcta o incorrecta -->
      <div class="col-12">
         @if(session('message'))
            <div class="alert alert-success">{{ session('message') }}</div>
         @endif

         @if(session('alert'))
            <div class="alert alert-danger">{{ session('alert') }}</div>
         @endif

   <!-- Formulario para filtrar por plataforma -->
   <div class="form-group row">
   <!-- Formulario para filtrar por Titulo -->
      <form action="FiltrarTitulo" method="POST" class="form-inline">
               <div class="form-group mx-sm-3 mb-2">
                  @csrf
                  <input type="text" name="titulo" class="form-control" placeholder="Titulo" >
               </div>
               <button type="submit" class="btn btn-primary mb-2">Filtrar</button>
            </form>

      <form action="filtrar" method="POST" class="form-inline">
            <div class="form-group mx-sm-3 mb-2">
               @csrf
                  <select name="plataforma" id="1" class="form-control form-control-sm">
                     @foreach ($plataformas as $plataforma)
                        <option value="{{ $plataforma->nombre }}">{{$plataforma->nombre}}</option>
                     @endforeach
                  </select>
            </div>
            <button type="submit" class="btn btn-primary mb-2">Filtrar</button>           
      </form>
       </div>
         
          <table class="table table-bordered table-dark table-hover text-center justifi-content-center" id="laravel_crud">
           <thead>
              <tr>
               <th>Imagen</th>
               <th>Titulo</th>
               <th>Género</th>
               <th>Edicion</th>
               <th>Plataforma</th>
               <th>Precio</th>
               <td colspan="1">Action</td>
              </tr>
           </thead>
           <tbody>
              @foreach($games as $game)
              <tr>
                  <td><img src="{{ asset('storage'). '/' . $game->foto }}" width="100" height="140" class="rounded img-fluid" alt=""></td>
                 <td class="align-middle">{{ $game->titulo }}</td>
                 <td class="align-middle">{{ $game->genero }}</td>
                 <td class="align-middle">{{ $game->edicion }}</td>
                 <td class="align-middle">{{ $game->plataforma }}</td>
                 <td class="align-middle" >{{ $game->precio }}€</td>
                 <td class="align-middle"><a href="{{ route('games.comprar',$game->id)}}" class="btn btn-success">Comprar</a></td>
              </tr>
              @endforeach
           </tbody>
          </table>
       </div>
       <div class="ml-3">
         {{ $games->links() }} 
       </div>
       
   </div>
 @endsection

CódigoProyecto/resources/views/game/Show.blade.php
@extends('layouts.app')

@section('content')
<h2 style="margin-top: 12px;" class="text-center">Pagina de Compra</a></h2>


<form action="{{ route('payment') }}" method="POST" name="update_game">
@csrf
<div class="">
        
    <div class="col-md-8">
        <div class="form-group">
            <strong>Titulo</strong>
            <input type="text" name="titulo" class="form-control" placeholder="Titulo" value="{{ $game_info->titulo }}" readonly>
            <span class="text-danger">{{ $errors->first('titulo') }}</span>
        </div>
    </div>
    <div class="col-md-8">
        <div class="form-group">
            <strong>Genero</strong>
            <input type="text" name="genero" class="form-control" placeholder="Genero" value="{{ $game_info->genero }}" readonly>
            <span class="text-danger">{{ $errors->first('genero') }}</span>
        </div>
    </div>
    <div class="col-md-8">
        <div class="form-group">
            <strong>Edicion</strong>
            <input type="text" name="edicion" class="form-control" placeholder="Edicion" value="{{ $game_info->edicion }}" readonly>
            <span class="text-danger">{{ $errors->first('edicion') }}</span>
        </div>
    </div>
    <div class="col-md-8">
        <div class="form-group">
            <strong>Plataforma</strong>
            <input type="text" name="plataforma" class="form-control" placeholder="Plataforma" value="{{ $game_info->plataforma }}" readonly>
            <span class="text-danger">{{ $errors->first('plataforma') }}</span>
        </div>
    </div>

    <div class="col-md-8">
        <div class="form-group">
            <input type="hidden" name="precio" class="form-control" placeholder="Precio" value="{{ $game_info->precio }}"  readonly>
            <span class="text-danger">{{ $errors->first('precio') }}</span>
        </div>
    </div>

    <div class="col-md-8 text-center">

        <input type="submit" value="Pagar  {{ $game_info->precio }}€"  class="btn btn-success col-md-2">
    
    </div>
</div>

</form>
@endsection